### ISSUE TITLE
Cannot add contact to group

### ISSUE THREAD

**Issue by chok-github** [smithahm/PhoneBookWebApp#1]
I'm not able to add contacts to groups. I see a stack trace as below, when I click on Add to Group button under Contacts.

Would you be able to fix this and resubmit?

[qtp1769660010-38] ERROR spark.webserver.MatcherFilter - 
java.lang.NullPointerException
        at com.webapp.phonebook.Group.<init>(Group.java:15)
        at com.webapp.phonebook.GroupService.find(GroupService.java:37)
        at com.webapp.phonebook.GroupService.update(GroupService.java:60)
        at com.webapp.phonebook.GroupResource$6.handle(GroupResource.java:61)
        at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
        at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:144)
        at spark.webserver.JettyHandler.doHandle(JettyHandler.java:54)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:179)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:451)
        at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:252)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:266)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:240)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
        at java.lang.Thread.run(Thread.java:745)

**Comment by smithahm** [comment]
@chok-tplink I will work on this issue and get back to you. Thanks
